default: &default
  adapter: mysql2
  encoding: utf8mb4
  charset: utf8mb4
  collation: utf8mb4_unicode_ci
  username: <%= ENV['DB_USERNAME'] || 'root' %>
  password: <%= ENV['DB_PASSWORD'] %>
  host: <%= ENV['DB_HOST'] || '127.0.0.1' %>
  port: 3306

development:
  <<: *default
  database: short_url_development

test:
  <<: *default
  database: short_url_test

production:
  <<: *default
  database: short_url_production
  username: short_url
  password: <%= ENV["SHORT_URL_DATABASE_PASSWORD"] %>
